/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

public Plugin:myinfo = 
{
	name = "Build Blocker",
	author = "DWN",
	description = "Stops buildings",
	version = "1.0",
	url = "http://www.topnotchclan.com"
}

public OnPluginStart()
{
	if (!AddCommandListener(Listener, "build"))
	{
		SetFailState("Build command listener failed");
	}
}

public OnMapStart()
{
	PrecacheSound("vo/announcer_failure.wav");
}

public Action:Listener(client, const String:command[], argc)
{
	EmitSoundToClient(client, "vo/announcer_failure.wav");	
	return Plugin_Continue;
}