/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

public Plugin:myinfo = 
{
	name = "Command Responder",
	author = "DWN",
	description = "Responds to Commands",
	version = "1.0",
	url = "http://www.topnotchclan.com"
}

public OnPluginStart()
{
	if (!AddCommandListener(Listener, "say"))
	{
		SetFailState("Say command listener failed");
	}
	if (!AddCommandListener(Listener, "say_team"))
	{
		SetFailState("Say_team command listener failed");
	}
}

public OnMapStart()
{
	PrecacheSound("vo/announcer_failure.wav");
}


public Action:Listener(client, const String:command[], argc)
{
	new String:text[192]
	if (!GetCmdArgString(text, sizeof(text)))
	{
		return Plugin_Continue;
	}
 
	// compensate for quotation marks
	new startidx = 0;
	if(text[strlen(text)-1] == '"')
	{
		text[strlen(text)-1] = '\0';
		startidx = 1;
	}
 
	if (strcmp(text[startidx], "!rtv", false) ==0)
	{
		if (LibraryExists("rockthevote"))
		{
			EmitSoundToClient(client, "vo/announcer_failure.wav");
			PrintToChat(client, "\x04Fail: \x03There is no RTV on a 24/7 single map server!");
			return Plugin_Handled;
		}
	}
	
	if (strcmp(text[startidx], "!rtd", false) ==0 || strcmp(text[startidx], "/rtd", false) ==0 || strcmp(text[startidx], "rtd", false) ==0)
	{
		EmitSoundToClient(client, "vo/announcer_failure.wav");
		PrintToChat(client, "\x04Fail: \x03This server does not run mods that give players advantages over others!");
		/* Block the client's messsage from broadcasting */
		return Plugin_Handled
	}
 
	/* Let say continue normally */
	return Plugin_Continue;
}