/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Heartbeater",
	author = "DWN",
	description = "Heartbeats my server",
	version = "1.0",
	url = "topnotchclan.com"
}

public OnPluginStart()
{
	CreateTimer(0.1, heartbeat, TIMER_REPEAT);
}

public Action:heartbeat(Handle:timer) {
	ServerCommand("heartbeat");
}
